name       : python-pycountry
version    : 20.7.3
release    : 7
source     :
    - https://files.pythonhosted.org/packages/76/73/6f1a412f14f68c273feea29a6ea9b9f1e268177d32e0e69ad6790d306312/pycountry-20.7.3.tar.gz : 81084a53d3454344c0292deebc20fcd0a1488c136d4900312cbd465cf552cb42
license    : LGPL-2.1-or-later
component  : programming.python
summary    : ISO country, subdivision, language, currency and script definitions and their translations
description: |
    ISO country, subdivision, language, currency and script definitions and their translations
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
