name       : python-pycountry
version    : 19.8.18
release    : 4
source     :
    - https://files.pythonhosted.org/packages/16/b6/154fe93072051d8ce7bf197690957b6d0ac9a21d51c9a1d05bd7c6fdb16f/pycountry-19.8.18.tar.gz : 3c57aa40adcf293d59bebaffbe60d8c39976fba78d846a018dc0c2ec9c6cb3cb
license    : LGPL-2.1-or-later
component  : programming.python
summary    : ISO country, subdivision, language, currency and script definitions and their translations
description: |
    ISO country, subdivision, language, currency and script definitions and their translations
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
