name       : python-pycountry
version    : 17.1.8
release    : 1
source     :
    - https://pypi.python.org/packages/4b/51/9155a48faed108db64a0ff45227c752fda8126f3585475cef30b7abaa536/pycountry-17.1.8.tar.gz : c5ccad49e47caee92779bf83da81565159b1fe3d8f48b063068ac118b73dd1f8
license    : GPL-2.0
component  : programming.python
summary    : ISO country, subdivision, language, currency and script definitions and their translations
description: |
    ISO country, subdivision, language, currency and script definitions and their translations
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
