name       : python-pycountry
version    : 22.1.10
release    : 8
source     :
    - https://pypi.python.org/packages/source/p/pycountry/pycountry-22.1.10.tar.gz : b9a6d9cdbf53f81ccdf73f6f5de01b0d8493cab2213a230af3e34458de85ea32
license    : LGPL-2.1-or-later
component  : programming.python
summary    : ISO country, subdivision, language, currency and script definitions and their translations
description: |
    ISO country, subdivision, language, currency and script definitions and their translations
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
