name       : python-pycountry
version    : 18.12.8
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pycountry/pycountry-18.12.8.tar.gz : 8ec4020b2b15cd410893d573820d42ee12fe50365332e58c0975c953b60a16de
license    : LGPL-2.1-or-later
component  : programming.python
summary    : ISO country, subdivision, language, currency and script definitions and their translations
description: |
    ISO country, subdivision, language, currency and script definitions and their translations
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
